# Generated by Django 3.1.4 on 2020-12-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0002_catrgory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='caregory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menue.catrgory'),
        ),
    ]
