# Generated by Django 3.1.4 on 2020-12-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0003_product_caregory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catrgory',
            new_name='Catergory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='caregory',
            new_name='category',
        ),
    ]
