# Generated by Django 3.1.4 on 2021-01-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0004_auto_20201230_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
