# Generated by Django 3.1.4 on 2021-01-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0006_auto_20210108_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergory',
            new_name='Categories',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
