# Generated by Django 3.1.4 on 2021-01-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0007_auto_20210114_0852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
